### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by mosabua** [karlmdavis/ksoap2-android#1]
On clean checkout as of today doing a mvn clean install results in two test failures.

  testFaultDeserialize(org.ksoap2.SoapFaultTest)
  testFaultSerialize(org.ksoap2.SoapFaultTest)

let me know if you need more details.

**Comment by cffz0225** [comment]
Do you know the Date type how to set the getPropertyInfo(int arg0, Hashtable arg1, PropertyInfo arg2){    arg2.type = MarshalDate.DATE_CLASS } ，That is true? but my server alaways fault ：“Could not convert java.lang.String to bean field 'docStartDate', type java.util.Date “ and " argument type mismatch" ,thanks!
